[general]
static=yes
writeprotect=no

[from-issabel]
exten => s,1,NoOp(IVR-turnos desde troncal)
 same => n,Goto(farmacia-turno,s,1)
exten => 8000,1,Goto(farmacia-turno,s,1)
exten => _X.,1,NoOp(INVITE ${EXTEN} desde troncal)
 same => n,Goto(farmacia-turno,s,1)

#include "extensions_farmacias.conf"
