[general]
static=yes
writeprotect=no

[from-issabel]
exten => s,1,NoOp(IVR IP EMI&MAC desde troncal Issabel)
 same => n,Goto(farmacia-turno,s,1)
exten => 449700,1,Goto(farmacia-turno,s,1)
exten => _X.,1,NoOp(INVITE ${EXTEN} desde Issabel)
 same => n,Goto(farmacia-turno,s,1)

#include "extensions_farmacias.conf"
